# Generated by Django 4.2.3 on 2023-07-27 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name'], name='organizatio_name_2d216c_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['description'], name='organizatio_descrip_7a9219_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['email', 'contact'], name='organizatio_email_675ea3_idx'),
        ),
    ]
