# Generated by Django 4.2.1 on 2023-06-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatou', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendeurs',
            name='categorie',
            field=models.ManyToManyField(blank=True, null=True, to='yatou.categorie'),
        ),
    ]
