# Generated by Django 4.2.1 on 2023-06-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatou', '0002_alter_vendeurs_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendeurs',
            name='categorie',
            field=models.ManyToManyField(blank=True, default=[1], to='yatou.categorie'),
        ),
        migrations.AlterField(
            model_name='vendeurs',
            name='requetes',
            field=models.ManyToManyField(blank=True, default=[1], to='yatou.requetes'),
        ),
    ]
