# Generated by Django 4.2.1 on 2023-06-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatou', '0003_alter_vendeurs_categorie_alter_vendeurs_requetes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='NKENKE EYEBE', max_length=50, verbose_name='Nom du responsabe')),
                ('prenom', models.CharField(default='Samuel', max_length=50, verbose_name='Prénom du responsabe')),
                ('Date', models.DateField(auto_now=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'responsable',
                'verbose_name_plural': 'responsables',
            },
        ),
    ]
