# Generated by Django 4.2.1 on 2023-06-07 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yatou', '0004_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsable',
            name='proprio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
