# Generated by Django 4.2.1 on 2023-06-07 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yatou', '0005_responsable_proprio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Aucun nom', max_length=50, verbose_name='Nom de la boutique')),
                ('phone', models.IntegerField(default=0, verbose_name='Téléphone de la boutique')),
                ('office_adresse', models.CharField(blank=True, default='Mindoubé 1', max_length=50, null=True, verbose_name='Lieu de vente')),
                ('Date', models.DateField(auto_now=True, verbose_name='Date de création')),
                ('categorie', models.ManyToManyField(blank=True, default=[1], to='yatou.categorie')),
                ('proprio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requetes', models.ManyToManyField(blank=True, default=[1], to='yatou.requetes')),
            ],
            options={
                'verbose_name': 'responsable',
                'verbose_name_plural': 'responsables',
            },
        ),
        migrations.DeleteModel(
            name='Responsable',
        ),
    ]
